// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEmailService is an autogenerated mock type for the EmailService type
type MockEmailService struct {
	mock.Mock
}

type MockEmailService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailService) EXPECT() *MockEmailService_Expecter {
	return &MockEmailService_Expecter{mock: &_m.Mock}
}

// SendPIN provides a mock function with given fields: c, toEmail, pinCode
func (_m *MockEmailService) SendPIN(c context.Context, toEmail string, pinCode string) error {
	ret := _m.Called(c, toEmail, pinCode)

	if len(ret) == 0 {
		panic("no return value specified for SendPIN")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(c, toEmail, pinCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmailService_SendPIN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPIN'
type MockEmailService_SendPIN_Call struct {
	*mock.Call
}

// SendPIN is a helper method to define mock.On call
//   - c context.Context
//   - toEmail string
//   - pinCode string
func (_e *MockEmailService_Expecter) SendPIN(c interface{}, toEmail interface{}, pinCode interface{}) *MockEmailService_SendPIN_Call {
	return &MockEmailService_SendPIN_Call{Call: _e.mock.On("SendPIN", c, toEmail, pinCode)}
}

func (_c *MockEmailService_SendPIN_Call) Run(run func(c context.Context, toEmail string, pinCode string)) *MockEmailService_SendPIN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockEmailService_SendPIN_Call) Return(_a0 error) *MockEmailService_SendPIN_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmailService_SendPIN_Call) RunAndReturn(run func(context.Context, string, string) error) *MockEmailService_SendPIN_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmailService creates a new instance of MockEmailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailService {
	mock := &MockEmailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
