// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Simpolette/HeartSteal/server/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockSessionRepository is an autogenerated mock type for the SessionRepository type
type MockSessionRepository struct {
	mock.Mock
}

type MockSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepository) EXPECT() *MockSessionRepository_Expecter {
	return &MockSessionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: c, session
func (_m *MockSessionRepository) Create(c context.Context, session *domain.Session) error {
	ret := _m.Called(c, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Session) error); ok {
		r0 = rf(c, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - c context.Context
//   - session *domain.Session
func (_e *MockSessionRepository_Expecter) Create(c interface{}, session interface{}) *MockSessionRepository_Create_Call {
	return &MockSessionRepository_Create_Call{Call: _e.mock.On("Create", c, session)}
}

func (_c *MockSessionRepository_Create_Call) Run(run func(c context.Context, session *domain.Session)) *MockSessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Session))
	})
	return _c
}

func (_c *MockSessionRepository_Create_Call) Return(_a0 error) *MockSessionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Session) error) *MockSessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllByUserID provides a mock function with given fields: c, userID
func (_m *MockSessionRepository) DeleteAllByUserID(c context.Context, userID string) error {
	ret := _m.Called(c, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRepository_DeleteAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllByUserID'
type MockSessionRepository_DeleteAllByUserID_Call struct {
	*mock.Call
}

// DeleteAllByUserID is a helper method to define mock.On call
//   - c context.Context
//   - userID string
func (_e *MockSessionRepository_Expecter) DeleteAllByUserID(c interface{}, userID interface{}) *MockSessionRepository_DeleteAllByUserID_Call {
	return &MockSessionRepository_DeleteAllByUserID_Call{Call: _e.mock.On("DeleteAllByUserID", c, userID)}
}

func (_c *MockSessionRepository_DeleteAllByUserID_Call) Run(run func(c context.Context, userID string)) *MockSessionRepository_DeleteAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionRepository_DeleteAllByUserID_Call) Return(_a0 error) *MockSessionRepository_DeleteAllByUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRepository_DeleteAllByUserID_Call) RunAndReturn(run func(context.Context, string) error) *MockSessionRepository_DeleteAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function with given fields: c, id
func (_m *MockSessionRepository) DeleteByID(c context.Context, id string) error {
	ret := _m.Called(c, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockSessionRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - c context.Context
//   - id string
func (_e *MockSessionRepository_Expecter) DeleteByID(c interface{}, id interface{}) *MockSessionRepository_DeleteByID_Call {
	return &MockSessionRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", c, id)}
}

func (_c *MockSessionRepository_DeleteByID_Call) Run(run func(c context.Context, id string)) *MockSessionRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionRepository_DeleteByID_Call) Return(_a0 error) *MockSessionRepository_DeleteByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRepository_DeleteByID_Call) RunAndReturn(run func(context.Context, string) error) *MockSessionRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: c, id
func (_m *MockSessionRepository) GetByID(c context.Context, id string) (*domain.Session, error) {
	ret := _m.Called(c, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Session, error)); ok {
		return rf(c, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Session); ok {
		r0 = rf(c, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockSessionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - c context.Context
//   - id string
func (_e *MockSessionRepository_Expecter) GetByID(c interface{}, id interface{}) *MockSessionRepository_GetByID_Call {
	return &MockSessionRepository_GetByID_Call{Call: _e.mock.On("GetByID", c, id)}
}

func (_c *MockSessionRepository_GetByID_Call) Run(run func(c context.Context, id string)) *MockSessionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionRepository_GetByID_Call) Return(_a0 *domain.Session, _a1 error) *MockSessionRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*domain.Session, error)) *MockSessionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: c, userID
func (_m *MockSessionRepository) GetByUserID(c context.Context, userID string) ([]*domain.Session, error) {
	ret := _m.Called(c, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Session, error)); ok {
		return rf(c, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.Session); ok {
		r0 = rf(c, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockSessionRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - c context.Context
//   - userID string
func (_e *MockSessionRepository_Expecter) GetByUserID(c interface{}, userID interface{}) *MockSessionRepository_GetByUserID_Call {
	return &MockSessionRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", c, userID)}
}

func (_c *MockSessionRepository_GetByUserID_Call) Run(run func(c context.Context, userID string)) *MockSessionRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionRepository_GetByUserID_Call) Return(_a0 []*domain.Session, _a1 error) *MockSessionRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, string) ([]*domain.Session, error)) *MockSessionRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionRepository creates a new instance of MockSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepository {
	mock := &MockSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
