// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Simpolette/HeartSteal/server/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockVerificationPINRepository is an autogenerated mock type for the VerificationPINRepository type
type MockVerificationPINRepository struct {
	mock.Mock
}

type MockVerificationPINRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerificationPINRepository) EXPECT() *MockVerificationPINRepository_Expecter {
	return &MockVerificationPINRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: c, pin
func (_m *MockVerificationPINRepository) Create(c context.Context, pin *domain.VerificationPIN) error {
	ret := _m.Called(c, pin)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.VerificationPIN) error); ok {
		r0 = rf(c, pin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVerificationPINRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockVerificationPINRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - c context.Context
//   - pin *domain.VerificationPIN
func (_e *MockVerificationPINRepository_Expecter) Create(c interface{}, pin interface{}) *MockVerificationPINRepository_Create_Call {
	return &MockVerificationPINRepository_Create_Call{Call: _e.mock.On("Create", c, pin)}
}

func (_c *MockVerificationPINRepository_Create_Call) Run(run func(c context.Context, pin *domain.VerificationPIN)) *MockVerificationPINRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.VerificationPIN))
	})
	return _c
}

func (_c *MockVerificationPINRepository_Create_Call) Return(_a0 error) *MockVerificationPINRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVerificationPINRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.VerificationPIN) error) *MockVerificationPINRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserIDAndType provides a mock function with given fields: c, userID, pinType
func (_m *MockVerificationPINRepository) DeleteByUserIDAndType(c context.Context, userID string, pinType string) error {
	ret := _m.Called(c, userID, pinType)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserIDAndType")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(c, userID, pinType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVerificationPINRepository_DeleteByUserIDAndType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserIDAndType'
type MockVerificationPINRepository_DeleteByUserIDAndType_Call struct {
	*mock.Call
}

// DeleteByUserIDAndType is a helper method to define mock.On call
//   - c context.Context
//   - userID string
//   - pinType string
func (_e *MockVerificationPINRepository_Expecter) DeleteByUserIDAndType(c interface{}, userID interface{}, pinType interface{}) *MockVerificationPINRepository_DeleteByUserIDAndType_Call {
	return &MockVerificationPINRepository_DeleteByUserIDAndType_Call{Call: _e.mock.On("DeleteByUserIDAndType", c, userID, pinType)}
}

func (_c *MockVerificationPINRepository_DeleteByUserIDAndType_Call) Run(run func(c context.Context, userID string, pinType string)) *MockVerificationPINRepository_DeleteByUserIDAndType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockVerificationPINRepository_DeleteByUserIDAndType_Call) Return(_a0 error) *MockVerificationPINRepository_DeleteByUserIDAndType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVerificationPINRepository_DeleteByUserIDAndType_Call) RunAndReturn(run func(context.Context, string, string) error) *MockVerificationPINRepository_DeleteByUserIDAndType_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserIDAndType provides a mock function with given fields: c, userID, pinType
func (_m *MockVerificationPINRepository) GetByUserIDAndType(c context.Context, userID string, pinType string) (*domain.VerificationPIN, error) {
	ret := _m.Called(c, userID, pinType)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserIDAndType")
	}

	var r0 *domain.VerificationPIN
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.VerificationPIN, error)); ok {
		return rf(c, userID, pinType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.VerificationPIN); ok {
		r0 = rf(c, userID, pinType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.VerificationPIN)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(c, userID, pinType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVerificationPINRepository_GetByUserIDAndType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserIDAndType'
type MockVerificationPINRepository_GetByUserIDAndType_Call struct {
	*mock.Call
}

// GetByUserIDAndType is a helper method to define mock.On call
//   - c context.Context
//   - userID string
//   - pinType string
func (_e *MockVerificationPINRepository_Expecter) GetByUserIDAndType(c interface{}, userID interface{}, pinType interface{}) *MockVerificationPINRepository_GetByUserIDAndType_Call {
	return &MockVerificationPINRepository_GetByUserIDAndType_Call{Call: _e.mock.On("GetByUserIDAndType", c, userID, pinType)}
}

func (_c *MockVerificationPINRepository_GetByUserIDAndType_Call) Run(run func(c context.Context, userID string, pinType string)) *MockVerificationPINRepository_GetByUserIDAndType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockVerificationPINRepository_GetByUserIDAndType_Call) Return(_a0 *domain.VerificationPIN, _a1 error) *MockVerificationPINRepository_GetByUserIDAndType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVerificationPINRepository_GetByUserIDAndType_Call) RunAndReturn(run func(context.Context, string, string) (*domain.VerificationPIN, error)) *MockVerificationPINRepository_GetByUserIDAndType_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVerificationPINRepository creates a new instance of MockVerificationPINRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerificationPINRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerificationPINRepository {
	mock := &MockVerificationPINRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
